Metrics/LineLength:
  Max: 220
  AllowURI: true
  URISchemes:
    - http
    - https
Documentation:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Max: 10
Metrics/LineLength:
  Max: 1200
Metrics/ClassLength:
  Max: 1200
Metrics/MethodLength:
  Max: 1200
Metrics/ModuleLength:
  Max: 1200
Performance/CompareWithBlock:
  Enabled: true
Style/LeadingCommentSpace:
  Enabled: false
Style/SpaceBeforeComment:
  Enabled: false
Metrics/AbcSize:
  Enabled: true
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Lint/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
AllCops:
  UseCache: false
  Rails:
    Enabled: true
    TargetRubyVersion: 2.4
    TargetRailsVersion: 5.1
